spring.application.name=hospitalManagement


# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/hospitalDB
spring.datasource.username=shahnawaz
spring.datasource.password=Pass@123

server.servlet.context-path=/api/v1

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

#server.servlet.context-path=/api

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

# MySQL Dialect (optional in latest versions)
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
